algoritmo "semnome"
// Função :
// Autor :
// Data : 24/11/2017
// Seção de Declarações 
var
x,y:inteiro
procedimento soma(var a,b:inteiro)
inicio
a<-a+1
b<-b+2
escrevaL("O valor de A=",a)
escrevaL("O valor de B=",b)
escrevaL("A soma dos valores é",a+b)
fimprocedimento
inicio
// Seção de Comandos 
x<-4
y<-8
soma(x,y)
escrevaL("O valor de X=",x)
escrevaL("O valor de Y=",y)

fimalgoritmo
