algoritmo "semnome"
// Função :
// Autor :  Philipe
// Data : 15/11/2017
// Seção de Declarações 
var
idade:inteiro
inicio
// Seção de Comandos 
escreval("Descubra se você pode tira a carteira de motorista")
escreva("Em que ano você nasceu: ")
leia(idade)
idade<-2017-idade
escreval("Você tem ", idade," anos")
se (idade>17) entao
escreva("Você esta apto a dirigir")
senao
escreva("Você não esta apto a dirigir")
fimse
fimalgoritmo
