algoritmo "semnome"
// Função :
// Autor :
// Data : 16/11/2017
// Seção de Declarações
var
n,contador,salto:inteiro
inicio
// Seção de Comandos
escreva("Deseja conta até que numero: ")
leia(n)
escreva("Qual o valor do salto: ")
leia(salto)
contador<-0
enquanto (contador<=n) faca
escreval(contador,"...")
contador<-contador+salto
fimenquanto
escreval("...Contagem Finalizada")

fimalgoritmo
